Views
diegoh40/rails-blog-app pull request #8
Opened 2022-12-09 06:26 UTC by diegoh40

2022-12-09 08:13 UTC, FrederickMih requested changes
## Hi :raising_hand: @diegoh40 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


![](https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif)

## Highlights


- PR is descriptive :+1: 
- The five most recent comments were display on the post index page :+1: 
- No Linter error :heavy_check_mark: 


## Required Changes ♻️

- Let's kindly get rid of the Microverse logo on our README file. You can add your own logo or leave it empty. Also, fill the **? FAQ** section to make your README looks more descriptive and professional

_Check the comments under the review._

## Optional suggestions

- [**Optional**] To avoid the Rails default page from showing up when points to the URL(http://localhost:3000/), let's set the root routes to the index view page(`root "users#index"`) in the `routes.rb` file.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 08:13 UTC, FrederickMih commented on app/views/users/show.html.erb
> +<% @posts.each_with_index do |post, index|%>
- [ ] Based on the requirements of this project, we are supposed to retrieve and render the user's three most recent posts. Kindly fix :wrench: this. 
- **Hint** `<% @user.last_three.each do |post, index|%>`

- [ ] As mentioned above, you need a link(`See all Post`) at the bottom of the page. Clicking on the link should display all the user's posts as seen on this [wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_all_posts.png)

2022-12-09 08:13 UTC, FrederickMih commented on app/views/posts/show.html.erb
> +
- Once more, let's make our views look presentable as seen on the wireframes.

2022-12-09 12:08 UTC, diegoh40 commented on app/views/users/index.html.erb
> +</div>
Hi thanks for the advice but, if you notice the variable is different on each page, I should't do the same for all of them.

2022-12-09 15:22 UTC, cynthiainga requested changes
Hi @diegoh40, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

 ## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Correct Gitflow ✔️ 

 ## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇 👇 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 07:21 UTC, sumairq approved these changes
### Hi @diegoh40  , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 11:12 UTC, merged